name: check-test-cases

on:
  push:
    paths:
      - "Test Cases/**"

jobs:
  check-test-cases:
    name: check-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd CheckTestCases'
        run: ./build.cmd CheckTestCases
